version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "php artisan serve --host=0.0.0.0 --port=8998 & npm run dev"
        ports:
            - 5174:5174
            - 8998:8998
        networks:
            - crawler_network
        volumes:
            - .:/application
        depends_on:
            - mysql

    mysql:
        image: mysql
        ports:
            - 3308:3306
        networks:
            - crawler_network
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_DATABASE: laravel
        volumes:
            - mysql_data:/var/lib/mysql

networks:
    crawler_network:
volumes:
    mysql_data:
